//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: person.proto

package in.rk.models;

@kotlin.jvm.JvmSynthetic
public inline fun person(block: in.rk.models.PersonKt.Dsl.() -> kotlin.Unit): in.rk.models.Person =
  in.rk.models.PersonKt.Dsl._create(in.rk.models.Person.newBuilder()).apply { block() }._build()
public object PersonKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: in.rk.models.Person.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: in.rk.models.Person.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): in.rk.models.Person = _builder.build()

    /**
     * <code>string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <code>string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }

    /**
     * <code>int32 age = 2;</code>
     */
    public var age: kotlin.Int
      @JvmName("getAge")
      get() = _builder.getAge()
      @JvmName("setAge")
      set(value) {
        _builder.setAge(value)
      }
    /**
     * <code>int32 age = 2;</code>
     */
    public fun clearAge() {
      _builder.clearAge()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun in.rk.models.Person.copy(block: in.rk.models.PersonKt.Dsl.() -> kotlin.Unit): in.rk.models.Person =
  in.rk.models.PersonKt.Dsl._create(this.toBuilder()).apply { block() }._build()
